import { library } from "@fortawesome/fontawesome-svg-core"
import { faGithub } from "@fortawesome/free-brands-svg-icons"
import { faClock, faDizzy, faGrinTongueWink } from "@fortawesome/free-regular-svg-icons"
import {
  faBell,
  faBellSlash,
  faBomb,
  faChevronLeft,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleXmark,
  faCloudMoon,
  faCompactDisc,
  faExclamationCircle,
  faFilter,
  faGear,
  faMagnifyingGlass,
  faRedoAlt,
  faSpinner,
  faSun,
  faTriangleExclamation,
} from "@fortawesome/free-solid-svg-icons"

library.add(
  faBell,
  faBellSlash,
  faBomb,
  faChevronLeft,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleXmark,
  faCloudMoon,
  faCompactDisc,
  faExclamationCircle,
  faFilter,
  faGear,
  faMagnifyingGlass,
  faRedoAlt,
  faSpinner,
  faSun,
  faTriangleExclamation,
  faClock,
  faDizzy,
  faGrinTongueWink,
  faGithub,
)
