import { library } from "@fortawesome/fontawesome-svg-core"
import { faClock, faDizzy } from "@fortawesome/free-regular-svg-icons"
import {
  faAngleLeft,
  faBell,
  faBellSlash,
  faBomb,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleXmark,
  faCloudMoon,
  faCompactDisc,
  faExclamationCircle,
  faFilter,
  faGear,
  faMagnifyingGlass,
  faRedoAlt,
  faSpinner,
  faSun,
  faTriangleExclamation,
} from "@fortawesome/free-solid-svg-icons"

library.add(
  faAngleLeft,
  faBell,
  faBellSlash,
  faBomb,
  faCircle,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleXmark,
  faCloudMoon,
  faCompactDisc,
  faExclamationCircle,
  faFilter,
  faGear,
  faMagnifyingGlass,
  faRedoAlt,
  faSpinner,
  faSun,
  faTriangleExclamation,
  faClock,
  faDizzy,
)
